<a href="https://colab.research.google.com/github/Yogeswari-sri/Python-Coursework-From-Fundamentals-to-Data-Analytics/blob/main/Python_DA_Assignment_1_Data_Analysis_using_NumPy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Python DA Assignment 1: Data Analysis using NumPy and Pandas***

Tasks:
Numpy Array Operations:

In [ ]:
import numpy as np

In [ ]:
#1. Create a 1D NumPy Array:
temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [ ]:
#2. Inspection and Properties:
print(temperatures_w1)
# Data Types
print("Data Types",temperatures_w1.dtype)
# Shape
print("Shape",temperatures_w1.shape)
#Number of Elements
print("Number of Elements",temperatures_w1.size)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Data Types float64
Shape (7,)
Number of Elements 7

In [ ]:
# 3. Array Operations:
#● Convert the temperatures_w1 from Celsius to Fahrenheit using the formula:
Celsius=25
np.Fahrenheit = (Celsius * 9/5) + 32
print("Fahrenheit")

Fahrenheit

In [ ]:
# Find the maximum, minimum, and mean temperatures for the week.
print("Maximum_week",np.max(temperatures_w1))
print("minimum_week",np.min(temperatures_w1))
print("Mean_temperature_week",np.mean(temperatures_w1))

Maximum_week 26.1
minimum_week 20.8
Mean_temperature_week 23.542857142857144

4. Array Slicing and Indexing:

In [ ]:
# Extract the temperatures for the first three days of the week.
print("First 3 days of the week:", temperatures_w1[:3])
# Extract the temperatures for the weekend (last two days).
print("weekend_Temperatures:", temperatures_w1[-2:])
# Extract the temperatures for the middle three days of the week.
print("Middle 3 days of the week",temperatures_w1[2:5])

First 3 days of the week: [22.5 25.3 20.8]
weekend_Temperatures: [24.8 21.9]
Middle 3 days of the week [20.8 23.4 26.1]

5. Create a 2D Array:

In [ ]:
temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],      #week1
                      [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])       #week2
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

6. Inspect and Slice the 2D Array:

In [ ]:
# Inspect and print the shape, data type, and total number of elements in the temperatures array.
print("Shape of elements in the temperatures array",temperatures.shape)
print("Datatype of elements in the temperatures array",temperatures.dtype)
print("total number of elements in the temperatures array",temperatures.size)

Shape of elements in the temperatures array (2, 7)
Datatype of elements in the temperatures array float64
total number of elements in the temperatures array 14

In [ ]:
# Extract the temperatures for each week and the weekends (last two days) for both weeks.
print("extract the temperatures for both weeks\n",temperatures[:,-2:])

extract the temperatures for both weeks
 [[24.8 21.9]
 [22.8 20.1]]

Pandas Series:

**1. Creating Pandas Series:**

In [ ]:
import pandas as pd

In [ ]:
# Pandas Series
marks=pd.Series([95, 92, 89, 85, 80],
                index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print(marks)
print(type(marks))

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64
<class 'pandas.core.series.Series'>

**2. Indexing and Slicing:**

In [ ]:
# Use the integer index position to access the mark of the 1st rank student.
print(" 1st rank student \n",marks.iloc[0])
# Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their inde labels.
print("top 3 ranks \n",marks.iloc[0:3])
# Use the iloc accessor to retrieve the mark of the 3rd-ranked student.
print("retrieve the mark of the 3rd-ranked student \n",marks.iloc[2])
# Apply a boolean mask to filter the Series and retrieve the ranks where the marks ar greater than 90.
print("Ranks with marks > 90:\n", marks[marks > 90])

 1st rank student
 95
top 3 ranks
 Rank1    95
Rank2    92
Rank3    89
dtype: int64
retrieve the mark of the 3rd-ranked student
 89
Ranks with marks > 90:
 Rank1    95
Rank2    92
dtype: int64

**3. Manipulating Series:**

In [ ]:
# Modify the mark of the student with the 1st rank to 100.
marks["Rank1"]=100
print("Modifying data",marks)
# Remove the entry corresponding to the last rank from the Series.


marks = marks.drop("Rank5")
print("droping data",marks)
# Compute the CGPA by dividing each mark in the Series by 10.
CGPA=marks/10
print("CGPA",CGPA)

Modifying data Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64
droping data Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
CGPA Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

**Pandas DataFrame:

1. Creating Pandas DataFrame:**

In [ ]:
transactions={
    "TransactionID" : [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "ProductCategory" : ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing','Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    "Region" : ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South','North'],
    "Amount" : [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]

}
print(transactions)
df=pd.DataFrame(transactions)

{'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110], 'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'], 'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'], 'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]}

2**. Data Exploration:**

In [ ]:
#Display the transactions DataFrame and its basic information, including head, tail,shape, column names, and data types.
print("Head:", df.head())
print("Tail", df.tail())
print("Shape ", df.shape)
print("Column names", df.columns)
# Display only the 'ProductCategory' and 'Amount' columns.
print("ProductCategory & Amount:\n", df[["ProductCategory", "Amount"]])
# Retrieve the last 3 columns of the DataFrame using iloc or loc
print("Last 3 columns:\n", df.iloc[:, -3:])
# Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

print("Filter Region and Amount greater than 200:\n", df[(df["Region"] == "North") & (df["Amount"] > 200)])
# Find the value counts for the 'ProductCategory' column.
print("Value_Counts of Product Category",df["ProductCategory"].value_counts())
# Find the unique values in the 'Region' column.
print("Unique Region : ",df["Region"].unique())
# Group by 'Region' and find the mean amount for each region.
print("Region_Mean Using Groupby",df.groupby("Region")["Amount"].mean())

Head:    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
Tail    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
Shape  (10, 4)
Column names Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')
ProductCategory & Amount:
   ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400
Last 3 columns:
   ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400
Filter Region and Amount greater than 200:
    TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400
Value_Counts of Product Category ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64
Unique Region :  ['North' 'South' 'East' 'West']
Region_Mean Using Groupby Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

Manipulating the DataFrame:

● Modify the 'Amount' for the transaction with TransactionID 102 to 165.

● Add a new column 'Discount' by calculating 10% of the 'Amount'.

● Remove the row with TransactionID 109.

● Delete the 'Discount' column from the DataFrame.

In [ ]:
df.loc[df["TransactionID"] == 102, "Amount"] = 165
df

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [ ]:
df["Discount"]=df["Amount"] * 0.10
df

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [ ]:
# Remove row where TransactionID = 109
df = df[df["TransactionID"] != 109]
print(df)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [ ]:
# Drop Discount column
df.drop("Discount",axis=1,inplace = True)
print(df)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

/tmp/ipykernel_716/4104152672.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop("Discount",axis=1,inplace = True)